### ISSUE TITLE
Clarify relation with ManufacturingOntologies

### ISSUE THREAD

**Issue by rido-min** [JMayrbaeurl/opendigitaltwins-isa95#1]
Is this repo a fork of https://github.com/digitaltwinconsortium/ManufacturingOntologies ?

**Comment by JMayrbaeurl** [comment]
It's not a fork. It's the master or working repo. Releases of the complete ontology get copied to https://github.com/digitaltwinconsortium/ManufacturingOntologies/tree/main/Ontologies/ISA95

**Comment by rido-min** [comment]
thanks @JMayrbaeurl , is there any process to keep both repos in sync? 

/cc @barnstee

**Comment by JMayrbaeurl** [comment]
I'm using PRs

**Comment by rido-min** [comment]
The PRs came from https://github.com/JMayrbaeurl/ManufacturingOntologies not this repo.. or am I missing something?

**Comment by JMayrbaeurl** [comment]
No. Just to clarify the process:

1. All work for the DTDL models (changes, additions, ...) is done in this repo
2. Changes are copied over to my fork of the DTC ManufacturingOntologies repo
3. PR is created for the original DTC ManufacturingOntologies repo
4. Erich merges the PR
